## redis 配置
rogge:
  redis:
    # 模式 Pool 单节点  Cluster 集群 Sentinel 哨兵
    model: Pool
    # 节点
    nodes: 120.27.3.97:6379
    # 密码
    password:
    # 连接池中的最大连接数（使用负值表示没有限制）
    max-active: 1000
    # 连接池中的最大空闲连接
    max-idle: 10
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接超时时间
    connectionTimeout: 6000
    # 读取超时时间
    soTimeout: 6000
    # 超时重试次数:负数表示集群节点数
    max-attempts: 1