person:
  name: rogge
  sex: man
  age: 25

spring:
  application:
    name: data-multidatasource
  primary-datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rogge
    username: root
    password: 123456
  second-datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zheng
    username: root
    password: 123456

  # REDIS (RedisProperties)
  redis:
    database: 0         # Redis数据库索引（默认为0）
    host: localhost     # Redis服务器地址
    port: 6379          # Redis服务器连接端口
    password:           # Redis服务器连接密码（默认为空）
    pool.max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
    pool.max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-idle: 8    # 连接池中的最大空闲连接
    pool.min-idle: 0    # 连接池中的最小空闲连接
    timeout: 0          # 连接超时时间（毫秒）