server:
  port: 8081
  context-path: /main

spring:
  profiles:
    active: dev

  output:
    ansi:
      enabled: always   #多彩log

logging:
  level:
    com.rogge: debug
  file: ./logs/sb.log
  root: info
