person:
  name: rogge
  sex: man
  age: 25

spring:
  application:
    name: data-multidatasource
  primary-datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rogge
    username: root
    password: 123456
  second-datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zheng
    username: root
    password: 123456

  # REDIS (RedisProperties)
  redis:
    database: 0         # Redis数据库索引（默认为0）
    host: 192.168.0.31   # Redis服务器地址
    port: 6379          # Redis服务器连接端口
    password: "@#ASddasd123129:$)...asdsd{!dsdfsdfdf"
    pool.max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
    pool.max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-idle: 8    # 连接池中的最大空闲连接
    pool.min-idle: 0    # 连接池中的最小空闲连接
    timeout: 0          # 连接超时时间（毫秒）

apache:
  rocketmq:
    ###MQ服务器地址
    namesrvAddr: 106.53.210.178:9876;101.200.239.17:9876
    producer:
      ###生产者分组
      producerGroup: RoggeProducer
    ###消费者名称
    consumer:
      consumerGroup1: RoggeConsumer1

## redis 配置
rogge:
  redis:
    # 模式 Pool 单节点  Cluster 集群 Sentinel 哨兵
    model: Pool
    # 节点
    nodes: 192.168.0.31:6379
    # 密码
    password: "@#ASddasd123129:$)...asdsd{!dsdfsdfdf"
    # 连接池中的最大连接数（使用负值表示没有限制）
    max-active: 1000
    # 连接池中的最大空闲连接
    max-idle: 10
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接超时时间
    connectionTimeout: 6000
    # 读取超时时间
    soTimeout: 6000
    # 超时重试次数:负数表示集群节点数
    max-attempts: 1